export const CREATE_TWEET = 'CREATE_TWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const EDIT_TWEET = 'EDIT_TWEET';
export const LOAD_INITIAL_TWEETS = 'LOAD_INITIAL_TWEETS';
export const LOAD_MORE_TWEETS = 'LOAD_MORE_TWEETS';

export const LOAD_HASHTAGS = 'LOAD_HASHTAGS';

export const FIREBASE_LOGIN = 'FIREBASE_LOGIN';
export const FIREBASE_LOGOUT = 'FIREBASE_LOGOUT';
export const FIREBASE_SIGNUP = 'FIREBASE_SIGNUP';
export const FIREBASE_FORGOT_PASSWORD = 'FIREBASE_FORGOT_PASSWORD';
